name: Firebase
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npm i firebase-tools -g
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
